sudo: required

services:
  - docker

script:
  - "docker build -t aparcar/openwrt-x86_64:snapshot ./snapshots/x86/64/"

deploy:
  provider: script
  script: bash docker_push
  on:
    branch: master
