sudo: required

notifications:
  email: false

services:
  - docker

before_script:
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin

script:
  - curl -s "$BASE_URL/$ROOTFS_URL" | docker import - "$DOCKER_USERNAME/openwrt-rootfs:$TAG"
  - docker push "$DOCKER_USERNAME/openwrt-rootfs:$TAG"
  - docker build -t "$DOCKER_USERNAME/openwrt:$TAG"
        --build-arg "DOCKER_USERNAME=$DOCKER_USERNAME"
        --build-arg "TAG=$TAG" .
  - docker push "$DOCKER_USERNAME/openwrt:$TAG"

env:
  global:
  - BASE_URL="https://downloads.openwrt.org"
  matrix:
  - TAG="latest" ROOTFS_URL="snapshots/targets/x86/64/openwrt-x86-64-generic-rootfs.tar.gz"
  - TAG="stable" ROOTFS_URL="releases/17.01.4/targets/x86/64/lede-17.01.4-x86-64-generic-rootfs.tar.gz"
  - TAG="arm-latest" ROOTFS_URL="snapshots/targets/armvirt/64/openwrt-armvirt-64-default-rootfs.tar.gz"
